BEGIN;

ALTER TABLE resources_files
    ADD COLUMN IF NOT EXISTS kind VARCHAR(20) NOT NULL DEFAULT 'FILE';

ALTER TABLE resources_files
    ADD COLUMN IF NOT EXISTS mime_type VARCHAR(150);

ALTER TABLE resources_files
    ADD COLUMN IF NOT EXISTS content TEXT;

ALTER TABLE resources_files
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE resources_files
    ALTER COLUMN file_path DROP NOT NULL;

COMMIT;
